spring:
  application:
    name: greeting-service-maven
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
greeting-service-maven:
  greeting: "Olá"
  default-value: "Mundo"  
